const projects = [
    {
        id: "espresso",
        title: "Espresso Essence – Landing Pages",
        category: "Coffee / Service",
        image1: "Images/Portfolio/espresso-essence1.webp",
        image2: "Images/Portfolio/espresso-essence2.webp",
        description: "Developed two landing pages — one for the brand and one for a specific service — with high‑impact visuals and straightforward messaging.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Coffee / Service",
        team: "1 member",
        overview: "Developed two landing pages — one for the brand and one for a specific service — with high‑impact visuals and straightforward messaging.",
        tech: ["Mailerlite", "HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Clean conversion‑focused layouts", "Integrated with Mailerlite forms", "Fast load and responsive design"],
        process: "Designed and implemented high-conversion landing pages focusing on brand aesthetics and user engagement.",
        impact: "Increased engagement and lead capture through simplified, attractive landing experiences."
    },
    {
        id: "abrakadabra",
        title: "Abrakadabra – Kindergarten Redesign (Berlin, Germany)",
        category: "Education / Preschool",
        image1: "Images/Portfolio/abrakadabra1.webp",
        image2: "Images/Portfolio/abrakadabra2.webp",
        description: "Redesigned the kindergarten’s online presence to improve clarity, layout, and branding.",
        role: "Web Designer & Front‑End Developer",
        date: "[Add Date]",
        sector: "Education / Preschool",
        team: "1 member",
        overview: "Redesigned the kindergarten’s online presence to improve clarity, layout, and branding. The focus was on creating a friendly, readable, and accessible one‑page layout that reflects a child‑centric institution.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Clean, responsive layout for all devices", "Updated visual hierarchy and typography", "Smooth interactions and navigation"],
        process: "Focused on creating a child-friendly and accessible design while ensuring information is easy to find for parents.",
        impact: "Improved user experience and presentation for parents and visitors by making key information easily accessible."
    },
    {
        id: "rentalx",
        title: "RentalX – Real Estate Platform (UK)",
        category: "Real Estate",
        image1: "Images/Portfolio/rentalx1.webp",
        image2: "Images/Portfolio/rentalx2.webp",
        description: "Complex real estate site with listings, search filters, and backend integration. Converted to WordPress for easy content management.",
        role: "Full Stack Developer",
        date: "[Add Date]",
        sector: "Real Estate",
        team: "1 member",
        overview: "Complex real estate site with listings, search filters, and backend integration. Converted to WordPress for easy content management.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind", "WordPress"],
        features: ["Property listing modules", "Search and filtering", "Admin content control"],
        process: "Developed a custom property management solution and integrated it into a user-friendly WordPress theme.",
        impact: "Improved client’s ability to manage properties and user discovery experience."
    },
    {
        id: "techcare",
        title: "TechCare – Healthcare Dashboard",
        category: "Healthcare Tech",
        image1: "Images/Portfolio/techcare1.webp",
        image2: "Images/Portfolio/techcare2.webp",
        description: "Developed a comprehensive dashboard for doctors to track appointments, patients, schedules, messages, and transactions.",
        role: "Full Stack Developer",
        date: "[Add Date]",
        sector: "Healthcare Tech",
        team: "1 member",
        overview: "Developed a comprehensive dashboard for doctors to track appointments, patients, schedules, messages, and transactions with custom WordPress plugins and React components.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind", "React JS", "PHP", "WordPress"],
        features: ["Appointment & schedule management", "Messaging system", "Patient tracking"],
        process: "Built a robust dashboard to streamline clinic operations and improve data visibility for healthcare professionals.",
        impact: "Streamlined clinic operations and improved data visibility for healthcare professionals."
    },
    {
        id: "globewide",
        title: "GlobeWide – Travel / Services",
        category: "Travel / Services",
        image1: "Images/Portfolio/globewide1.webp",
        image2: "Images/Portfolio/globewide2.webp",
        description: "Built a responsive showcase site emphasizing travel services and key offerings.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Travel / Services",
        team: "1 member",
        overview: "Built a responsive showcase site emphasizing travel services and key offerings.",
        tech: ["HTML5", "CSS3", "JS", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Responsive layout", "Service overview"],
        process: "Designed a visually appealing platform to highlight travel destinations and services.",
        impact: "Improved discoverability and engagement for travel services."
    },
    {
        id: "wheatsheaf",
        title: "Whatshelf Brands",
        category: "Corporate",
        image1: "Images/Portfolio/wheatsheafbrands1.webp",
        image2: "Images/Portfolio/wheatsheafbrands2.webp",
        description: "Developed a responsive showcase site to highlight the brand and services.",
        role: "Front‑End Developer",
        date: "[Add Date]",
        sector: "[Use public info if available]",
        team: "1 member",
        overview: "Developed a responsive showcase site to highlight the brand and services.",
        tech: ["HTML5", "CSS3", "JS", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Responsive design", "Service highlights"],
        process: "Created a modern and responsive design to effectively communicate the brand's value proposition.",
        impact: "Improved brand presentation and user accessibility online."
    },
    {
        id: "macbookstore",
        title: "MacBook Store",
        category: "E-Commerce",
        image1: "Images/Portfolio/macbookstore1.webp",
        image2: "Images/Portfolio/macbookstore2.webp",
        description: "Specialized e-commerce store for Apple products and accessories.",
        role: "E-Commerce Developer",
        date: "2024",
        sector: "Retail",
        team: "1 member",
        overview: "Niche store for MacBook users.",
        tech: ["WooCommerce"],
        features: ["Product configuration", "Apple-style aesthetics", "Secure checkout"],
        process: "Recreated the premium feel of Apple's digital experience.",
        impact: "Captured niche market sales for accessories."
    },
    {
        id: "marzouk",
        title: "Marzouk Formation",
        category: "WordPress Website",
        image1: "Images/Portfolio/marzouk formation 1.webp",
        image2: "Images/Portfolio/marzouk formation 2.webp",
        description: "A multilingual WordPress site for a training agency helping people secure jobs in Germany.",
        role: "Full Stack Developer, UX/UI Designer",
        date: "April 2024 · 3 weeks",
        sector: "Education / Vocational Training",
        team: "1 member",
        overview: "Marzouk Formation is a WordPress website built entirely by me. The site offers services to help people secure work contracts in Germany.",
        tech: ["Figma", "WordPress", "PHP", "HTML5/CSS3", "JavaScript"],
        features: ["Multilingual content (AR/FR/DE)", "Eight vocational domains", "Responsive design"],
        process: "Started with discovery phase, developed site structure, sketched wireframes, and built custom WordPress theme.",
        impact: "Client was very satisfied with design and speed. Helps potential students clearly see their options."
    },
    {
        id: "berlincafe",
        title: "Berlin Cafe – Restaurant Showcase",
        category: "Café / Hospitality",
        image1: "Images/Portfolio/berlincafe1.webp",
        image2: "Images/Portfolio/berlincafe2.webp",
        description: "Built a showcase website to present the café’s offerings, atmosphere, and contact details with a focus on visual appeal and cross‑device performance.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Café / Hospitality",
        team: "1 member",
        overview: "Built a showcase website to present the café’s offerings, atmosphere, and contact details with a focus on visual appeal and cross‑device performance.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Responsive layout for all screens", "Highlighted services and menus", "Contact and location focus"],
        process: "Developed a visually engaging layout to showcase the cafe's atmosphere and menu options.",
        impact: "Improved discoverability and visitor interaction by providing a clear, professional online presence."
    },
    {
        id: "labasta",
        title: "La Basta – Restaurant (Amsterdam)",
        category: "Restaurant / Hospitality",
        image1: "Images/Portfolio/la-basta1.webp",
        image2: "Images/Portfolio/la-basta2.webp",
        description: "Created a responsive showcase site for the Amsterdam restaurant, emphasizing menu, ambiance, and reservations info for local and visiting diners.",
        role: "Front‑End Developer",
        date: "[Add Date]",
        sector: "Restaurant / Hospitality",
        team: "1 member",
        overview: "Created a responsive showcase site for the Amsterdam restaurant, emphasizing menu, ambiance, and reservations info for local and visiting diners.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Mobile‑optimized design", "Highlight sections for menu and ambience", "Contact and reservation info"],
        process: "Focused on creating an inviting online atmosphere that mirrors the restaurant's physical ambiance.",
        impact: "Improved online engagement and helped users quickly access essential restaurant details."
    },
    {
        id: "atoca",
        title: "Atoca – Restaurant Website (UK)",
        category: "Restaurant / Hospitality",
        image1: "Images/Portfolio/atoca1.webp",
        image2: "Images/Portfolio/atoca2.webp",
        description: "Developed a fully responsive site to showcase the restaurant’s menu, story, and ambiance.",
        role: "Front‑End Developer",
        date: "[Add Date]",
        sector: "Restaurant / Hospitality",
        team: "1 member",
        overview: "Developed a fully responsive site to showcase the restaurant’s menu, story, and ambiance. The design emphasizes readability and user engagement for both diners and search traffic.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Mobile‑first responsive design", "Menu highlights with clear calls to action", "Fast‑loading performance"],
        process: "Implemented a mobile-first approach to ensure a seamless experience for users on all devices.",
        impact: "Enhanced online visibility and helped potential customers quickly find key information, improving conversions from browsing to booking."
    },
    {
        id: "foray",
        title: "Foray Club – Café / Eatery",
        category: "Café / Hospitality",
        image1: "Images/Portfolio/foray-club1.webp",
        image2: "Images/Portfolio/foray-club2.webp",
        description: "Built a responsive showcase site to present the café’s offerings and atmosphere, with emphasis on visuals and ease of navigation.",
        role: "Front‑End Developer",
        date: "[Add Date]",
        sector: "Café / Hospitality",
        team: "1 member",
        overview: "Built a responsive showcase site to present the café’s offerings and atmosphere, with emphasis on visuals and ease of navigation.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Responsive layout", "Clear service descriptions", "Fast, lightweight pages"],
        process: "Created a clean and efficient layout to enhance content readability and site performance.",
        impact: "Strengthened the café’s online presence and accessibility for customers."
    },
    {
        id: "caffenaopli",
        title: "Cafe Napoli – Italy",
        category: "Café / Hospitality",
        image1: "Images/Portfolio/caffe-naopli1.webp",
        image2: "Images/Portfolio/caffe-naopli2.webp",
        description: "Developed a responsive showcase site tailored for the café’s brand and local visitor needs.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Café / Hospitality",
        team: "1 member",
        overview: "Developed a responsive showcase site tailored for the café’s brand and local visitor needs.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Mobile‑friendly layout", "Highlight of specialties and atmosphere", "Contact info focus"],
        process: "Designed a site that captures the local charm and brand identity of Cafe Napoli.",
        impact: "Enhanced discoverability and ease of use for potential customers."
    },
    {
        id: "palacess",
        title: "Palacess – Nigerian Food Restaurant (UK)",
        category: "Restaurant / Cultural Cuisine",
        image1: "Images/Portfolio/palacess1.webp",
        image2: "Images/Portfolio/palacess2.webp",
        description: "Showcase site for a UK restaurant specializing in Nigerian cuisine, focusing on menu and cultural experience.",
        role: "Front‑End Developer",
        date: "[Add Date]",
        sector: "Restaurant / Cultural Cuisine",
        team: "1 member",
        overview: "Showcase site for a UK restaurant specializing in Nigerian cuisine, focusing on menu and cultural experience.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Responsive design", "Menu and culture focus", "Visual branding"],
        process: "Developed a visually rich site that highlights the cultural heritage and culinary offerings.",
        impact: "Helped present the restaurant’s offerings to a wider audience and improved user engagement."
    },
    {
        id: "callanswering",
        title: "Call Answering – Landing Page",
        category: "Service/Communications",
        image1: "Images/Portfolio/callanswering1.webp",
        image2: "Images/Portfolio/callanswering2.webp",
        description: "Landing page promoting call answering services with clear messaging and contact focus.",
        role: "Front‑End Developer",
        date: "[Add Date]",
        sector: "Service/Communications",
        team: "1 member",
        overview: "Landing page promoting call answering services with clear messaging and contact focus.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Quick info delivery", "Responsive layout"],
        process: "Focused on clear communication and a streamlined user journey for potential clients.",
        impact: "Improved lead capture and service visibility."
    },
    {
        id: "electrohouse",
        title: "Electro House – E‑Commerce (Sweden)",
        category: "E‑Commerce",
        image1: "Images/Portfolio/Sony Headphones 1.webp",
        image2: "Images/Portfolio/Sony Headphones 1.webp",
        description: "E‑commerce store for Swedish tech accessories, later converted to WordPress + WooCommerce with payment and product management plugins.",
        role: "Full Stack Developer",
        date: "[Add Date]",
        sector: "E‑Commerce",
        team: "1 member",
        overview: "E‑commerce store for Swedish tech accessories, later converted to WordPress + WooCommerce with payment and product management plugins.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind", "WordPress", "WooCommerce"],
        features: ["Product catalog", "Checkout system", "Admin product management"],
        process: "Built a scalable e-commerce platform with a focus on user experience and easy administration.",
        impact: "Enabled online sales with a fully functional store and CMS backend."
    },
    {
        id: "elite",
        title: "Elite Taekwondo & Fitness – Club (Tangier, Morocco)",
        category: "Fitness / Sports",
        image1: "Images/Portfolio/elite1.webp",
        image2: "Images/Portfolio/elite2.webp",
        description: "Built a responsive site to present class info, schedules, and club details for the fitness community.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Fitness / Sports",
        team: "1 member",
        overview: "Built a responsive site to present class info, schedules, and club details for the fitness community.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Mobile‑friendly layout", "Service info focus"],
        process: "Designed an informative and energetic site to attract new members and keep current ones informed.",
        impact: "Improved club visibility and member engagement."
    },
    {
        id: "gastoreserve",
        title: "Gusto Reserve – WordPress Restaurant",
        category: "Restaurant / Reservations",
        image1: "Images/Portfolio/gastoreserve1.webp",
        image2: "Images/Portfolio/gastoreserve2.webp",
        description: "Developed a restaurant site with Elementor including reservation system, menu admin, and login/signup features.",
        role: "WordPress Developer",
        date: "[Add Date]",
        sector: "Restaurant / Reservations",
        team: "1 member",
        overview: "Developed a restaurant site with Elementor including reservation system, menu admin, and login/signup features.",
        tech: ["WordPress", "Elementor", "JS", "Tailwind", "Bootstrap"],
        features: ["Reservations", "Menu management"],
        process: "Leveraged WordPress and Elementor to build a flexible and easy-to-manage restaurant site.",
        impact: "Provided a functional restaurant website with backend control."
    },
    {
        id: "formaxis",
        title: "Formaxis – Language + Work Abroad Center (Tangier)",
        category: "Education / Services",
        image1: "Images/Portfolio/formaxis1.webp",
        image2: "Images/Portfolio/formaxis2.webp",
        description: "Responsive site for a language and work placement center to highlight services and programs.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Education / Services",
        team: "1 member",
        overview: "Responsive site for a language and work placement center to highlight services and programs.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Service overview", "Contact focus"],
        process: "Created a clear and professional online presence to effectively communicate the center's services.",
        impact: "Improved visibility and accessibility for prospective students."
    },
    {
        id: "tangiertours",
        title: "Tangier Tours – Tourism Services",
        category: "Tourism",
        image1: "Images/Portfolio/tangiertours1.webp",
        image2: "Images/Portfolio/tangiertours2.webp",
        description: "Showcase site for tourism services in Tangier with responsive layout and clear service descriptions.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Tourism",
        team: "1 member",
        overview: "Showcase site for tourism services in Tangier with responsive layout and clear service descriptions.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Mobile‑friendly layout", "Tour highlight sections"],
        process: "Designed a site to showcase the beauty of Tangier and make booking tours easy.",
        impact: "Enhanced online presence and service discovery."
    },
    {
        id: "rebajas",
        title: "Rebajas Tangier – Handicraft Store Showcase",
        category: "Retail / Artisan",
        image1: "Images/Portfolio/rebajas1.webp",
        image2: "Images/Portfolio/rebajas2.webp",
        description: "Showcase site for a local handicrafts store, highlighting products and store identity.",
        role: "Web Developer",
        date: "[Add Date]",
        sector: "Retail / Artisan",
        team: "1 member",
        overview: "Showcase site for a local handicrafts store, highlighting products and store identity.",
        tech: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "Tailwind"],
        features: ["Lightweight, responsive layout", "Product showcases"],
        process: "Built a showcase site to highlight the unique craftsmanship and products of the store.",
        impact: "Increased local visibility and easy user browsing."
    },
    {
        id: "healthhub",
        title: "Health Hub",
        category: "Web Application",
        image1: "Images/Portfolio/healthhub 1.webp",
        image2: "Images/Portfolio/healthhub 2.webp",
        description: "A full-stack PHP & MySQL web app that helps users find nearby doctors, view schedules, and read reviews.",
        role: "Full Stack Developer & Web Designer",
        date: "June 2023 · 2 months",
        sector: "Healthcare / Local Services",
        team: "1 member",
        overview: "This web application helps users in my city and country find doctors nearby, check their availability schedules, read reviews, and access detailed information about their practice locations.",
        tech: ["Figma", "PHP (OOP)", "MySQL", "Bootstrap", "jQuery"],
        features: ["Search dentists by location", "View real-time availability", "Access detailed profiles"],
        process: "Collaborated with a practicing dentist to understand user needs. Designed database schema and developed backend with PHP OOP.",
        impact: "Streamlined the process for patients to find and choose dentists. Enhanced local healthcare access."
    },
    {
        id: "feathers",
        title: "Feathers Nest",
        category: "E-Commerce",
        image1: "Images/Portfolio/birdy store 1.webp",
        image2: "Images/Portfolio/birdy store 2.webp",
        description: "A bright, pet-focused e-commerce front-end for food, toys, and accessories.",
        role: "Front-End Developer & Web Designer",
        date: "September 2024 · 1 month",
        sector: "E-Commerce / Pets",
        team: "1 member",
        overview: "Feathers Nest is a front-end e-commerce website focused on selling pet supplies. Includes a blog section.",
        tech: ["Figma", "Canva", "HTML5", "CSS3", "Bootstrap", "Tailwind"],
        features: ["Clean responsive design", "Attractive product sections", "Blog area"],
        process: "Brand identity research, visual concept in Figma, responsive front-end development with Bootstrap/Tailwind.",
        impact: "Strengthened portfolio with creative front-end project. Provided client with scalable web interface."
    },
    {
        id: "souqsaad",
        title: "Souq Saad",
        category: "E-Commerce",
        image1: "Images/Portfolio/souq saad 1.webp",
        image2: "Images/Portfolio/souq saad 2.webp",
        description: "A lifestyle e-commerce store built on YouCan with a custom brand identity.",
        role: "E-Commerce Owner & Store Designer",
        date: "December 2023 · 2 weeks",
        sector: "Online Retail",
        team: "1 member",
        overview: "Souq Saad is an e-commerce website I built using YouCan. Designed to offer a clean, modern shopping experience.",
        tech: ["YouCan", "Canva", "Photoshop", "Figma"],
        features: ["Personalized color palette", "Custom logo and banners", "Mobile-friendly"],
        process: "Planned structure, designed brand elements, customized YouCan theme, uploaded optimized visuals.",
        impact: "Gained hands-on e-commerce experience. Created consistent online identity."
    }
];
