const projects = [
    {
        id: "healthhub",
        title: "Health Hub",
        category: "Web Application",
        image1: "Images/Portfolio/healthhub 1.jpg",
        image2: "Images/Portfolio/healthhub 2.jpg",
        description: "A full-stack PHP & MySQL web app that helps users find nearby doctors, view schedules, and read reviews.",
        role: "Full Stack Developer & Web Designer",
        date: "June 2023 · 2 months",
        sector: "Healthcare / Local Services",
        team: "1 member",
        overview: "This web application helps users in my city and country find doctors nearby, check their availability schedules, read reviews, and access detailed information about their practice locations.",
        tech: ["Figma", "PHP (OOP)", "MySQL", "Bootstrap", "jQuery"],
        features: ["Search dentists by location", "View real-time availability", "Access detailed profiles"],
        process: "Collaborated with a practicing dentist to understand user needs. Designed database schema and developed backend with PHP OOP.",
        impact: "Streamlined the process for patients to find and choose dentists. Enhanced local healthcare access."
    },
    {
        id: "marzouk",
        title: "Marzouk Formation",
        category: "WordPress Website",
        image1: "Images/Portfolio/marzouk formation 1.png",
        image2: "Images/Portfolio/marzouk formation 2.png",
        description: "A multilingual WordPress site for a training agency helping people secure jobs in Germany.",
        role: "Full Stack Developer, UX/UI Designer",
        date: "April 2024 · 3 weeks",
        sector: "Education / Vocational Training",
        team: "1 member",
        overview: "Marzouk Formation is a WordPress website built entirely by me. The site offers services to help people secure work contracts in Germany.",
        tech: ["Figma", "WordPress", "PHP", "HTML5/CSS3", "JavaScript"],
        features: ["Multilingual content (AR/FR/DE)", "Eight vocational domains", "Responsive design"],
        process: "Started with discovery phase, developed site structure, sketched wireframes, and built custom WordPress theme.",
        impact: "Client was very satisfied with design and speed. Helps potential students clearly see their options."
    },
    {
        id: "feathers",
        title: "Feathers Nest",
        category: "E-Commerce",
        image1: "Images/Portfolio/birdy store 1.png",
        image2: "Images/Portfolio/birdy store 2.png",
        description: "A bright, pet-focused e-commerce front-end for food, toys, and accessories.",
        role: "Front-End Developer & Web Designer",
        date: "September 2024 · 1 month",
        sector: "E-Commerce / Pets",
        team: "1 member",
        overview: "Feathers Nest is a front-end e-commerce website focused on selling pet supplies. Includes a blog section.",
        tech: ["Figma", "Canva", "HTML5", "CSS3", "Bootstrap", "Tailwind"],
        features: ["Clean responsive design", "Attractive product sections", "Blog area"],
        process: "Brand identity research, visual concept in Figma, responsive front-end development with Bootstrap/Tailwind.",
        impact: "Strengthened portfolio with creative front-end project. Provided client with scalable web interface."
    },
    {
        id: "souqsaad",
        title: "Souq Saad",
        category: "E-Commerce",
        image1: "Images/Portfolio/souq saad 1.png",
        image2: "Images/Portfolio/souq saad 2.png",
        description: "A lifestyle e-commerce store built on YouCan with a custom brand identity.",
        role: "E-Commerce Owner & Store Designer",
        date: "December 2023 · 2 weeks",
        sector: "Online Retail",
        team: "1 member",
        overview: "Souq Saad is an e-commerce website I built using YouCan. Designed to offer a clean, modern shopping experience.",
        tech: ["YouCan", "Canva", "Photoshop", "Figma"],
        features: ["Personalized color palette", "Custom logo and banners", "Mobile-friendly"],
        process: "Planned structure, designed brand elements, customized YouCan theme, uploaded optimized visuals.",
        impact: "Gained hands-on e-commerce experience. Created consistent online identity."
    },
    {
        id: "abrakadabra",
        title: "Abrakadabra",
        category: "Creative Project",
        image1: "Images/Portfolio/abrakadabra1.png",
        image2: "Images/Portfolio/abrakadabra2.png",
        description: "A magical creative project featuring wild animations and stunning visuals.",
        role: "Lead Designer & Developer",
        date: "2024",
        sector: "Creative Arts",
        team: "1 member",
        overview: "An experimental project pushing the boundaries of web animations and interactive design.",
        tech: ["HTML5", "CSS3", "GSAP", "Three.js"],
        features: ["Advanced animations", "Interactive 3D elements", "Immersive experience"],
        process: "Explored new animation libraries and implemented complex visual effects.",
        impact: "Demonstrated advanced frontend capabilities and creative direction."
    },
    {
        id: "atoca",
        title: "Atoca",
        category: "Corporate Site",
        image1: "Images/Portfolio/atoca1.png",
        image2: "Images/Portfolio/atoca2.png",
        description: "A professional corporate website designed for a modern business identity.",
        role: "Web Developer",
        date: "2024",
        sector: "Business",
        team: "1 member",
        overview: "A sleek and professional presence for Atoca, focusing on clarity and brand communication.",
        tech: ["WordPress", "Elementor", "CSS3"],
        features: ["Clean layout", "Fast loading speeds", "SEO optimized"],
        process: "Developed custom theme based on client branding guidelines.",
        impact: "Increased online visibility and client inquiries."
    },
    {
        id: "berlincafe",
        title: "Berlin Cafe",
        category: "Hospitality",
        image1: "Images/Portfolio/berlincafe1.png",
        image2: "Images/Portfolio/berlincafe2.png",
        description: "A cozy and inviting website for a Berlin-based cafe.",
        role: "Web Designer",
        date: "2024",
        sector: "Food & Beverage",
        team: "1 member",
        overview: "Digital presence for Berlin Cafe, highlighting their menu and atmosphere.",
        tech: ["HTML", "SASS", "JavaScript"],
        features: ["Online menu", "Reservation system", "Gallery"],
        process: "Photography and web design combined to create a warm digital atmosphere.",
        impact: "Boosted foot traffic and table reservations."
    },
    {
        id: "espresso",
        title: "Espresso Essence",
        category: "E-Commerce",
        image1: "Images/Portfolio/espresso-essence1.png",
        image2: "Images/Portfolio/espresso-essence2.png",
        description: "Premium coffee bean store with a rich, aromatic design.",
        role: "Full Stack Developer",
        date: "2024",
        sector: "E-Commerce",
        team: "1 member",
        overview: "An e-commerce platform dedicated to premium coffee lovers.",
        tech: ["Shopify", "Liquid", "JS"],
        features: ["Product filtering", "Subscription model", "Brewing guides"],
        process: "Customized Shopify theme to match the premium brand aesthetic.",
        impact: "Established a strong direct-to-consumer sales channel."
    },
    {
        id: "labasta",
        title: "La Basta",
        category: "Restaurant",
        image1: "Images/Portfolio/la-basta1.png",
        image2: "Images/Portfolio/la-basta2.png",
        description: "Italian restaurant website featuring a dynamic menu and booking system.",
        role: "Frontend Developer",
        date: "2024",
        sector: "Food & Beverage",
        team: "1 member",
        overview: "A vibrant website for La Basta, an Italian eatery.",
        tech: ["React", "Node.js"],
        features: ["Interactive menu", "Table booking", "Event calendar"],
        process: "Built a fast single-page application for seamless user experience.",
        impact: "Improved improved customer engagement and booking efficiency."
    },
    {
        id: "foray",
        title: "Foray Club",
        category: "Lifestyle",
        image1: "Images/Portfolio/foray-club1.png",
        image2: "Images/Portfolio/foray-club2.png",
        description: "Exclusive club membership portal with heavy visual focus.",
        role: "UI/UX Designer",
        date: "2024",
        sector: "Lifestyle",
        team: "1 member",
        overview: "Membership portal for Foray Club, offering exclusive access and content.",
        tech: ["Vue.js", "Firebase"],
        features: ["Member login", "Exclusive content", "Event registration"],
        process: "Focused on high-end aesthetics and exclusive user flows.",
        impact: "Successfully launched the digital membership tier."
    },
    {
        id: "caffenaopli",
        title: "Caffe Naopli",
        category: "Hospitality",
        image1: "Images/Portfolio/caffe-naopli1.png",
        image2: "Images/Portfolio/caffe-naopli2.png",
        description: "Authentic Neapolitan coffee experience brought to the web.",
        role: "Web Developer",
        date: "2024",
        sector: "Hospitality",
        team: "1 member",
        overview: "Website for Caffe Naopli, emphasizing tradition and quality.",
        tech: ["HTML5", "Bootstrap 5"],
        features: ["Storytelling section", "Menu download", "Location finder"],
        process: "Translated the physical ambiance of the cafe into a digital format.",
        impact: "Strengthened brand loyalty and local presence."
    },
    {
        id: "palacess",
        title: "Palacess",
        category: "Real Estate",
        image1: "Images/Portfolio/palacess1.png",
        image2: "Images/Portfolio/palacess2.png",
        description: "Luxury real estate listings with virtual tour capabilities.",
        role: "Frontend Engineer",
        date: "2024",
        sector: "Real Estate",
        team: "1 member",
        overview: "High-end real estate platform for luxury properties.",
        tech: ["Next.js", "Tailwind CSS"],
        features: ["Virtual tours", "High-res gallery", "Agent contact"],
        process: "Optimized for high-quality image delivery and fast browsing.",
        impact: "Facilitated high-value property inquiries."
    },
    {
        id: "rentalx",
        title: "RentalX",
        category: "Automotive",
        image1: "Images/Portfolio/rentalx1.png",
        image2: "Images/Portfolio/rentalx2.png",
        description: "Modern car rental platform with instant booking engine.",
        role: "Full Stack Developer",
        date: "2024",
        sector: "Automotive",
        team: "1 member",
        overview: "Car rental platform designed for speed and convenience.",
        tech: ["MERN Stack"],
        features: ["Real-time availability", "Secure payments", "User dashboard"],
        process: "Built a robust booking engine with availability management.",
        impact: "Automated the rental booking process."
    },
    {
        id: "wheatsheaf",
        title: "Wheatsheaf Brands",
        category: "Corporate",
        image1: "Images/Portfolio/wheatsheafbrands1.png",
        image2: "Images/Portfolio/wheatsheafbrands2.png",
        description: "Corporate portfolio for a group of heritage brands.",
        role: "Web Designer",
        date: "2024",
        sector: "Business",
        team: "1 member",
        overview: "Consolidated digital presence for Wheatsheaf Brands.",
        tech: ["WordPress", "PHP"],
        features: ["Brand portfolio", "Investor relations", "News section"],
        process: "Unified multiple brand identities into a cohesive corporate site.",
        impact: " improved corporate communication and brand cohesion."
    },
    {
        id: "globewide",
        title: "GlobeWide",
        category: "Travel",
        image1: "Images/Portfolio/globewide1.png",
        image2: "Images/Portfolio/globewide2.png",
        description: "International travel agency portal with destination guides.",
        role: "Frontend Developer",
        date: "2024",
        sector: "Travel & Tourism",
        team: "1 member",
        overview: "Travel portal inspiring users to explore global destinations.",
        tech: ["React", "API Integration"],
        features: ["Search destinations", "Booking integration", "Travel blog"],
        process: "Integrated 3rd party travel APIs for real-time data.",
        impact: "Increased booking conversions through inspirational content."
    },
    {
        id: "techcare",
        title: "TechCare",
        category: "Technology",
        image1: "Images/Portfolio/techcare1.png",
        image2: "Images/Portfolio/techcare2.png",
        description: "IT support and services website for business solutions.",
        role: "Web Developer",
        date: "2024",
        sector: "Technology",
        team: "1 member",
        overview: "B2B website for IT support services.",
        tech: ["HTML", "CSS", "JS"],
        features: ["Service catalog", "Support ticket system link", "Client testimonials"],
        process: "Focused on trust and professional reliability in design.",
        impact: "Generated B2B leads for IT services."
    },
    {
        id: "callanswering",
        title: "Call Answering",
        category: "Business Services",
        image1: "Images/Portfolio/callanswering1.png",
        image2: "Images/Portfolio/callanswering2.png",
        description: "Professional answering service landing page optimized for conversion.",
        role: "CRO Specialist",
        date: "2024",
        sector: "Business Services",
        team: "1 member",
        overview: "Landing page for a call answering service.",
        tech: ["Unbounce", "Custom CSS"],
        features: ["A/B tested layout", "Lead capture forms", "Benefit highlights"],
        process: "Designed for high conversion rates with clear CTAs.",
        impact: "Improved lead generation efficiency."
    },
    {
        id: "macbookstore",
        title: "MacBook Store",
        category: "E-Commerce",
        image1: "Images/Portfolio/macbookstore1.png",
        image2: "Images/Portfolio/macbookstore2.png",
        description: "Specialized e-commerce store for Apple products and accessories.",
        role: "E-Commerce Developer",
        date: "2024",
        sector: "Retail",
        team: "1 member",
        overview: "Niche store for MacBook users.",
        tech: ["WooCommerce"],
        features: ["Product configuration", "Apple-style aesthetics", "Secure checkout"],
        process: "Recreated the premium feel of Apple's digital experience.",
        impact: "Captured niche market sales for accessories."
    },
    {
        id: "elite",
        title: "Elite",
        category: "Fashion",
        image1: "Images/Portfolio/elite1.png",
        image2: "Images/Portfolio/elite2.png",
        description: "High-fashion brand portfolio and lookbook.",
        role: "Visual Designer",
        date: "2024",
        sector: "Fashion",
        team: "1 member",
        overview: "Digital lookbook for Elite fashion brand.",
        tech: ["Webflow"],
        features: ["Fullscreen imagery", "Smooth scroll", "Lookbook gallery"],
        process: "Prioritized visual impact and smooth motion.",
        impact: "Elevated brand perception in the fashion space."
    },
    {
        id: "gastoreserve",
        title: "Gusto Reserve",
        category: "Food & Beverage",
        image1: "Images/Portfolio/gastoreserve1.png",
        image2: "Images/Portfolio/gastoreserve2.png",
        description: "Premium reservation platform for fine dining.",
        role: "UX Designer",
        date: "2024",
        sector: "Hospitality",
        team: "1 member",
        overview: "Reservation management for high-end restaurants.",
        tech: ["React Native" , "Firebase"],
        features: ["Table selection", "Pre-order menu", "VIP management"],
        process: "Designed complex flows for table management.",
        impact: "Reduced no-shows and improved guest experience."
    },
    {
        id: "formaxis",
        title: "Formaxis",
        category: "Architecture",
        image1: "Images/Portfolio/formaxis1.png",
        image2: "Images/Portfolio/formaxis2.png",
        description: "Minimalist architecture firm portfolio.",
        role: "Front-End Developer",
        date: "2024",
        sector: "Architecture",
        team: "1 member",
        overview: "Portfolio for Formaxis architects.",
        tech: ["Gatsby", "Structured Data"],
        features: ["Project case studies", "Minimal grid", "Fast performance"],
        process: "Built a lightning-fast static site to showcase high-res architectural photos.",
        impact: "Global reach for architectural projects."
    },
    {
        id: "tangiertours",
        title: "Tangier Tours",
        category: "Tourism",
        image1: "Images/Portfolio/tangiertours1.png",
        image2: "Images/Portfolio/tangiertours2.png",
        description: "Local tourism guide and booking site for Tangier.",
        role: "Local Consultant & Dev",
        date: "2024",
        sector: "Tourism",
        team: "1 member",
        overview: "The ultimate guide to visiting Tangier.",
        tech: ["WordPress", "Maps API"],
        features: ["Interactive map", "Tour packages", "Local tips"],
        process: "Curated local experiences and integrated booking capabilities.",
        impact: "Boosted local tourism bookings."
    },
    {
        id: "rebajas",
        title: "Rebajas",
        category: "E-Commerce",
        image1: "Images/Portfolio/rebajas1.png",
        image2: "Images/Portfolio/rebajas2.png",
        description: "Discount and deals aggregator platform.",
        role: "Full Stack Developer",
        date: "2024",
        sector: "Retail",
        team: "1 member",
        overview: "Platform for finding the best deals and discounts.",
        tech: ["Laravel", "Vue.js"],
        features: ["Deal expiration", "Category filtering", "User submissions"],
        process: "Built a high-traffic platform for deal hunting.",
        impact: "Created a community of deal hunters."
    }
];
